### Pancake main configuration
main:
### System settings
  TmpPath: ../tmp/                                              # Path for temporary files
  Logging:
    System: ../log/system.log                                   # Path to system log file
    Request: ../log/requests.log                                # Path to request log file
    Error: ../log/error.log                                     # Path to error log file
  DateFormat: 'Y-m-d H:i:s'                                     # See php.net/date for more information on date formatting
  DebugMode: false                                              # Enable Pancake debug mode
  User: www-data                                                # System user
  Group: www-data                                               # System group
  ExposePancake: true                                           # Expose Pancake in Server header and system messages
  SizePrefix: bin                                               # "si" or "bin" - SI: 1000 Byte = 1 Kilobyte - Binary: 1024 Byte = 1 Kibibyte
 
### Network interface settings
## Use 0 to listen on all available IPv4 interfaces
  IPv4:                                                         # IPv4 network interfaces
    - 0
## Use ::0 to listen on all available IPv6 and IPv4 interfaces
  IPv6:                                                         # IPv6 network interfaces
    - ::0
  ListenPorts:                                                  # List of TCP ports to listen on
    - 80
  SocketBacklog: 200                                            # Connection backlog for incoming requests
  NaglesAlgorithm: false                                        # Enable or disable TCP Nagle's algorithm (will set TCP_NODELAY when false)
  MaxConcurrent: 0                                              # Concurrent connection limit (0 for no limit)

### Network buffering settings
  PreBuffer: 65536                                              # Buffer static file data in RAM before sending HTTP headers (can save one write cycle)
  WriteBufferMin: 10240                                         # Minimum write buffer size
  WriteLimit: 1048576                                           # Maximum write buffer size
  WriteBufferSoftMaxConcurrent: 50                              # Soft concurrent write buffer limit - When this limit is reached, Pancake won't allocate any buffers that are bigger than WriteBufferMin
  WriteBufferHardMaxConcurrent: 2000                            # Hard concurrent write buffer limit - When this limit is reached, Pancake will try not to allocate any buffers at all

### Pancake worker settings
  RequestWorkers: 2                                             # Amount of RequestWorkers to run
  RequestWorkerLimit: 350000                                    # Request processing limit for RequestWorkers (0 for no limit)
  WaitPHPWorkerBoot: true                                       # Wait for PHPWorkers to boot (should be disabled in shared environments)
  WorkerBootTime: 5                                             # Maximum time in seconds for a worker to boot

### HTTP settings
  AllowHEAD: true                                               # Enable HTTP HEAD
  AllowTRACE: false                                             # Enable HTTP TRACE
  AllowOPTIONS: false                                           # Enable HTTP OPTIONS

### Additional configuration files
include:
  - ../conf/vhosts/
  - ../conf/mime.yml
  
### Moody PHP Preprocessor settings
moody:
  DeleteWhitespaces: false
  DeleteComments: true
  
### FastCGI upstream server configurations
FastCGI:
## Example configuration for using php-fpm instead of Pancake SAPI for PHP execution
#  php:
#    multiplex: true
#    type: unix
#    address: /var/run/php5-fpm.socket
#    mimeTypes:
#      - text/x-php

### AJP13 upstream server configurations
AJP13:
## Example configuration for proxying Jenkins through Pancake
#  jenkins:
#    type: ipv4
#    address: 127.0.0.1
#    port: 1030
#    maxconcurrent: 100

### Secure Socket Layer settings
TLS:
#  CertificateChain: /etc/ssl/certs/myCert.crt                  # SSL/TLS Certificate chain 
#  PrivateKey: /etc/ssl/private/myKey.key                       # Private key
#  CipherList: ECDHE-RSA-AES128-SHA256:AES128-GCM-SHA256:RC4:HIGH:!MD5:!aNULL:!EDH # List of allowed ciphers (see man ciphers(1))
#  Options:                                                     # Options for OpenSSL library
#    - SSL_OP_NO_COMPRESSION                                    # You should disable SSL compression in order to prevent CRIME attacks
#    - SSL_OP_CIPHER_SERVER_PREFERENCE                          # This setting will cause Pancake to honor the cipher list order
#  Ports:                                                       # Ports used for SSL/TLS connections
#    - 443
